#!/usr/bin/env node
/**
 * fetch-adhkar.js — build the morning & evening adhkar data from an open,
 * redistributable Ḥiṣn al-Muslim dataset (authentic Qur'an + hadith text,
 * the same collection used by islambook.com and most adhkar apps).
 *
 * No dependencies. Requires Node 18+ (built-in fetch).
 *
 *   node scripts/fetch-adhkar.js
 *
 * Source: github.com/osamayy/azkar-db (azkar.json) — SQL-export shape:
 *   columns: [category, zekr, description, count, reference, search]
 *
 * Output (app format): data/morning-adhkar.js, data/evening-adhkar.js
 *   { id, text, fadl, source, count, remaining, category }
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SRC = "https://raw.githubusercontent.com/osamayy/azkar-db/master/azkar.json";

const CATS = [
  { key: "أذكار الصباح", out: "morning-adhkar.js", global: "MorningAdhkar", cat: "صباح" },
  { key: "أذكار المساء", out: "evening-adhkar.js", global: "EveningAdhkar", cat: "مساء" }
];

function clean(s) {
  return String(s || "")
    .replace(/\r/g, "")
    .replace(/[ \t]+/g, " ")
    .replace(/ *\n */g, "\n")
    .trim();
}

function mapRows(rows, cat) {
  // rows: [category, zekr, description, count, reference, search]
  return rows.map((r, i) => {
    const count = parseInt(r[3], 10) || 1;
    const item = {
      id: i + 1,
      text: clean(r[1]),
      count: count,
      remaining: count,
      category: cat
    };
    const fadl = clean(r[2]);
    const source = clean(r[4]);
    if (fadl) item.fadl = fadl;
    if (source) item.source = source;
    return item;
  });
}

async function main() {
  process.stdout.write("→ Fetching adhkar dataset … ");
  const res = await fetch(SRC, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error("HTTP " + res.status);
  const db = await res.json();
  console.log("ok");

  if (!db.rows || !db.columns) throw new Error("unexpected dataset shape");
  const ci = {};
  db.columns.forEach((c, i) => { ci[c.name] = i; });

  for (const c of CATS) {
    const rows = db.rows.filter((r) => r[ci.category] === c.key);
    if (!rows.length) throw new Error("no rows for category " + c.key);
    const items = mapRows(rows, c.cat);
    const banner =
      "/**\n" +
      " * " + c.key + " — GENERATED by scripts/fetch-adhkar.js from the\n" +
      " * Ḥiṣn al-Muslim dataset (osamayy/azkar-db). Order preserved.\n" +
      " * Each item: { id, text, fadl?, source?, count, remaining, category }\n" +
      " */\n";
    fs.writeFileSync(
      path.join(ROOT, "data", c.out),
      banner + "window." + c.global + " = " + JSON.stringify(items, null, 2) + ";\n"
    );
    console.log("✓ data/" + c.out + " — " + items.length + " items");
  }

  console.log("\nDone. Bump CACHE_VERSION in service-worker.js so clients refresh.");
}

main().catch((e) => {
  console.error("\n✗ Failed: " + e.message);
  process.exit(1);
});
