#!/usr/bin/env node
/**
 * fetch-quran.js — download the full Holy Quran (Uthmani Arabic) and write it
 * as clean, simple JSON files.
 *
 * No dependencies. Requires Node 18+ (uses the built-in fetch).
 *
 *   node scripts/fetch-quran.js
 *
 * Outputs:
 *   quran/001.json … quran/114.json   one file per surah (the "separate folder")
 *   quran/index.json                  lightweight list of all 114 surahs
 *   data/quran-data.js                regenerates window.QuranText for the app
 *
 * Per-surah file format (simple and self-describing):
 *   {
 *     "number": 2,
 *     "name": "البقرة",
 *     "type": "مدنية",
 *     "ayahCount": 286,
 *     "bismillah": true,
 *     "ayahs": [ { "n": 1, "text": "الم" }, ... ]
 *   }
 *
 * Source: api.alquran.cloud (edition: quran-uthmani). Free, widely used.
 * Always verify against a trusted Mushaf before publishing.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const https = require("https");

const ROOT = path.resolve(__dirname, "..");
const QURAN_DIR = path.join(ROOT, "quran");
const DATA_FILE = path.join(ROOT, "data", "quran-data.js");

// Primary + fallback sources (both return Arabic Uthmani text).
const SOURCES = [
  "https://api.alquran.cloud/v1/quran/quran-uthmani",
  "https://cdn.jsdelivr.net/gh/islamic-network/cdn@master/info/quran-uthmani.json"
];

function pad(n) { return String(n).padStart(3, "0"); }

// Map English revelation type → Arabic.
function arType(t) {
  return /medin/i.test(t) ? "مدنية" : "مكية";
}

// Strip the leading "سورة " prefix the API includes in surah names.
function cleanName(name) {
  return String(name).replace(/^سُورَةُ\s+/, "").replace(/^سورة\s+/, "").trim();
}

// Fetch JSON with a small retry + manual https fallback for old Node.
async function getJSON(url) {
  if (typeof fetch === "function") {
    const res = await fetch(url, { headers: { "accept": "application/json" } });
    if (!res.ok) throw new Error("HTTP " + res.status + " for " + url);
    return res.json();
  }
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode !== 200) { reject(new Error("HTTP " + res.statusCode)); return; }
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => { try { resolve(JSON.parse(data)); } catch (e) { reject(e); } });
    }).on("error", reject);
  });
}

async function download() {
  let lastErr;
  for (const url of SOURCES) {
    try {
      process.stdout.write("→ Fetching from " + url + " … ");
      const json = await getJSON(url);
      const surahs = (json.data && json.data.surahs) || json.surahs;
      if (!Array.isArray(surahs) || surahs.length !== 114) {
        throw new Error("unexpected shape (" + (surahs ? surahs.length : "none") + " surahs)");
      }
      console.log("ok");
      return surahs;
    } catch (e) {
      console.log("failed (" + e.message + ")");
      lastErr = e;
    }
  }
  throw lastErr || new Error("All sources failed");
}

function toSurahFile(s) {
  const number = s.number;
  const ayahs = s.ayahs.map((a) => ({
    n: a.numberInSurah != null ? a.numberInSurah : a.number,
    text: String(a.text).trim(),
    // Physical Madani-mushaf page (1..604) — used by the reader to paginate by
    // the real Quran page layout. Also keep the juz' for context.
    page: a.page,
    juz: a.juz
  }));
  // Al-Fatihah counts the basmalah as ayah 1; At-Tawbah (9) has none.
  // Every other surah is shown with a separate basmalah line in the reader.
  const bismillah = number !== 1 && number !== 9;
  return {
    number,
    name: cleanName(s.name),
    type: arType(s.revelationType || s.type || ""),
    ayahCount: ayahs.length,
    bismillah,
    ayahs
  };
}

function writeAppData(surahFiles) {
  const map = {};
  for (const s of surahFiles) {
    map[s.number] = { bismillah: s.bismillah, ayahs: s.ayahs };
  }
  const banner =
    "/**\n" +
    " * Quran verse text — GENERATED by scripts/fetch-quran.js.\n" +
    " * Do not edit by hand; re-run the script to refresh.\n" +
    " * window.QuranText[surahNumber] = { bismillah, ayahs:[{n,text}] }\n" +
    " */\n";
  fs.writeFileSync(DATA_FILE, banner + "window.QuranText = " + JSON.stringify(map) + ";\n");
}

async function main() {
  fs.mkdirSync(QURAN_DIR, { recursive: true });

  const surahs = await download();
  const files = surahs
    .slice()
    .sort((a, b) => a.number - b.number)
    .map(toSurahFile);

  // This edition prepends the Basmalah inside ayah 1 of every surah. Since the
  // reader shows it as a separate line (bismillah:true), strip that leading
  // Basmalah from the first ayah so it isn't displayed twice. Al-Fatihah's
  // ayah 1 *is* the Basmalah, so we use it as the canonical prefix to strip.
  const basmalah = files[0].ayahs[0].text.trim();
  for (const s of files) {
    if (s.bismillah && s.ayahs.length && s.ayahs[0].text.startsWith(basmalah)) {
      s.ayahs[0].text = s.ayahs[0].text.slice(basmalah.length).trim();
    }
  }

  // Per-surah files.
  let totalAyahs = 0;
  for (const s of files) {
    totalAyahs += s.ayahCount;
    fs.writeFileSync(
      path.join(QURAN_DIR, pad(s.number) + ".json"),
      JSON.stringify(s, null, 2) + "\n"
    );
  }

  // Lightweight index.
  const index = files.map((s) => ({
    number: s.number, name: s.name, type: s.type, ayahCount: s.ayahCount,
    file: "quran/" + pad(s.number) + ".json"
  }));
  fs.writeFileSync(path.join(QURAN_DIR, "index.json"), JSON.stringify(index, null, 2) + "\n");

  // Regenerate the app's data file so the reader shows everything immediately.
  writeAppData(files);

  console.log("\n✓ Wrote " + files.length + " surah files to  quran/");
  console.log("✓ Wrote  quran/index.json");
  console.log("✓ Regenerated  data/quran-data.js  (" + totalAyahs + " ayahs)");
  if (totalAyahs !== 6236) {
    console.log("⚠ Expected 6236 ayahs — got " + totalAyahs + ". Verify the source.");
  }
  console.log("\nNext: bump CACHE_VERSION in service-worker.js so clients refresh the cache.");
}

main().catch((e) => {
  console.error("\n✗ Failed: " + e.message);
  console.error("  Check your internet connection, or edit SOURCES in this script.");
  process.exit(1);
});
